version: '3.8'

services:
  azuresqledge:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: azuresqledge
    cap_add:
      - SYS_PTRACE
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: mypassword_123
    ports:
      - "1433:1433"
    volumes:
      - azuresqledge_data:/var/opt/mssql

volumes:
  postgres_data:
  azuresqledge_data:
