name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup .NET Core SDK (use .NET 8.0)
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      # Build the project to ensure .NET is working properly
      - name: Build the project
        run: dotnet build ./TemporalTables --configuration Release
      
      # Publish the project
      - name: Publish the project
        run: dotnet publish ./TemporalTables --configuration Release --output /app/publish

      # Setup Docker Buildx for multi-platform support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build and push the multi-platform Docker image
      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ${{ secrets.DOCKER_USERNAME }}/historization-prototype:latest \
            -f ./Dockerfile .  # Make sure it points to the right Dockerfile location